name: Test Workers

on:
  workflow_dispatch:

jobs:
  worker:
    name: Worker ${{ matrix.id }}

    strategy:
      fail-fast: false
      max-parallel: 20

      matrix:
        id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

    runs-on: ubuntu-latest

    steps:
      - name: Download worker code
        uses: actions/checkout@v4

      - name: Check PHP
        run: |
          php --version
          php -m
          php -r "var_dump(function_exists('curl_init'));"

      - name: Run worker
        run: |
          php -d display_errors=1 -d error_reporting=E_ALL worker.php
