name: PHP Test

on:
  workflow_dispatch:

jobs:
  worker:
    name: Worker ${{ matrix.id }}

    strategy:
      fail-fast: false
      max-parallel: 20

      matrix:
        id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: PHP diagnostics
        run: |
          echo "===== PHP ====="
          which php
          php --version

          echo "===== CURL ====="
          php -r 'var_dump(function_exists("curl_init"));'

          echo "===== FILE ====="
          ls -la
          echo "===== WORKER ====="
          ls -l worker.php

      - name: Run worker with error capture
        continue-on-error: true
        run: |
          echo "===== RUNNING WORKER ====="

          php \
            -d display_errors=1 \
            -d display_startup_errors=1 \
            -d error_reporting=E_ALL \
            worker.php 2>&1

          CODE=$?

          echo "===== PHP EXIT CODE: $CODE ====="

          exit 0
